name: Wake Railway App

on:
  schedule:
    # Wake before 11:20 job
    - cron: "45 5 * * 1-5"

    # Wake before 13:20 job
    - cron: "45 7 * * 1-5"

    # Wake before 15:20 job
    - cron: "45 9 * * 1-5"

    # Wake before 16:00 job
    - cron: "25 10 * * 1-5"

jobs:
  wake-server:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Railway App
        run: |
          curl -L nifty-dashboard-production.up.railway.app